package com.example.my_app.node.controller;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.my_app.node.dto.MemoResponse;
import com.example.my_app.node.service.NodeService;


@RestController
@RequestMapping("/api/v1")
public class NodeController {
    private final NodeService nodeService;

    public NodeController(NodeService nodeService){
        this.nodeService = nodeService;
    }

    
    @GetMapping("/memo/suppose/{id}")
    public ResponseEntity<Map<String, String>> suggestMemo(@PathVariable("id") Long nodeId) {
        
        String rootText = nodeService.getRootNodeText(nodeId);
        String currentText = nodeService.getCurrentNodeText(nodeId);

        String suggestion = "%s\n\n%s".formatted(rootText, currentText);  // 프롬프트 구조 예시
        Map<String, String> response = new HashMap<>();
        response.put("suggestion generated by LLM", suggestion);

        return ResponseEntity.ok(response);
    }

}
