package com.example.my_app.node.controller;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.my_app.node.domain.Node;
import com.example.my_app.node.service.NodeService;


@RestController
@RequestMapping("/api/v1")
public class NodeController {
    private final NodeService nodeService;
    //private final AIService aiService;

    public NodeController(NodeService nodeService /*  AIService aiService */ ){
        this.nodeService = nodeService;
        //this.aiService = aiService;
    }

    public record NodeDto(Long id, String nodeText, String memoText, Boolean isActive, Long parentId) {}

    // 프로젝트가 가진 노드 조회
    // 이건 프로젝트 쪽으로 이사 가야할 거 같은데? 
    @GetMapping("/projects/{projectId}/nodes")
    public ResponseEntity<List<NodeDto>> getNodes(@PathVariable Long projectId) {
        List<NodeDto> nodes = nodeService.getNodesByProjectId(projectId)
            .stream()
            .map(n -> new NodeDto(n.getId(), n.getNodeText(), n.getMemoText(), n.getIsActive(), n.getParent() != null ? n.getParent().getId() : null))
            .toList();
        return ResponseEntity.ok(nodes);
    }
    
    
    // 제안하기 버튼 클릭 시 호출 
    @GetMapping("/memo/suppose/{id}")
    public ResponseEntity<List<String>> suggestMemo(@PathVariable("id") Long nodeId) {
        //return 통일 안 하고 얘는 왜 제멋대로 List<String> 이냐고요? 제 맘입니다
        String rootText = nodeService.getRootNodeText(nodeId);
        String currentText = nodeService.getCurrentNodeText(nodeId);

        List<String> variables  = Arrays.asList(currentText);
        List<String> suggestion = Arrays.asList("idea generated by LLM");

        ////api key x
        //List<String> suggestion = aiService.generateNewIdeas(rootText,variables);
        
        return ResponseEntity.ok(suggestion);
    }

}
